Add player jump and lateral movement
FerchusGames/towerfall-clean-code pull request #2
Opened 2024-07-18 17:01 UTC by FerchusGames

2024-07-18 18:02 UTC, Horothenic requested changes

2024-07-18 18:02 UTC, Horothenic commented on Towerfall/Assets/_Main/Scripts/Player/PlayerController.cs
> +        [SerializeField] private PlayerPropertiesSO _playerProperties;
Esto tiene que ser injectado en `PlayerManager` y multiplicado antes de que llegue aqui :D
Osea la fuerza del salto y la fuerza del movimiento llegan aqui ya listos.

2024-07-18 18:02 UTC, Horothenic commented on Towerfall/Assets/_Main/Scripts/Player/PlayerController.cs
> +        [SerializeField] private PlayerPropertiesSO _playerProperties;
Investiga como hacer Bind a un ScriptableObject.

2024-07-19 00:10 UTC, Horothenic requested changes

2024-07-19 00:10 UTC, Horothenic commented on Towerfall/Assets/_Main/Scripts/Player/PlayerManager.cs
> +    }
Asi no XD
El lo aplica directo antes de enviarlo al controller.

2024-07-22 19:56 UTC, FerchusGames commented on Towerfall/Assets/_Main/Scripts/Player/PlayerController.cs
> +        [SerializeField] private PlayerPropertiesSO _playerProperties;
Listo, el PlayerManager procesa directamente el input y se lo manda al PlayerController.

2024-07-22 20:04 UTC, Horothenic approved these changes

2024-07-23 21:10 UTC, merged